# Generated by Django 3.1.6 on 2021-02-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_ordemservico'),
        ('plano', '0002_auto_20210128_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Justificativa',
        ),
        migrations.AddField(
            model_name='produto',
            name='justificativa',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='justificativa',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.atividade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.grupoatividade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.tipoatividade'),
        ),
        migrations.DeleteModel(
            name='Justificativa',
        ),
    ]
