# Generated by Django 3.1.1 on 2021-01-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_atividade', models.CharField(max_length=200)),
                ('pacto_minimo_reducao', models.IntegerField()),
                ('inativo', models.BooleanField()),
                ('descricao_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grupo_atividade', models.CharField(max_length=200)),
                ('inativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tipo_pacto', models.CharField(max_length=200)),
            ],
        ),
    ]
