# Generated by Django 3.1.1 on 2021-01-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20210118_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
