# Generated by Django 3.1.1 on 2021-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(max_length=200)),
                ('texto_explicativo', models.CharField(max_length=300)),
                ('duracao_faixa', models.FloatField()),
                ('duracao_faixa_presencial', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
