# Generated by Django 3.1.1 on 2021-01-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configurations', '0006_auto_20210119_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade_TipoPacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacto_exteriror', models.BooleanField()),
                ('tipo_pacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.tipopacto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGrupolUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioPerfilUnidade',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='id_unidade_superior',
        ),
        migrations.AddField(
            model_name='grupoatividade',
            name='atividades',
            field=models.ManyToManyField(to='configurations.Atividade'),
        ),
        migrations.AddField(
            model_name='tipoatividade',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configurations.atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidade',
            name='unidade_superior',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='configurations.unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariogrupolunidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.unidade'),
        ),
        migrations.AddField(
            model_name='usuariogrupolunidade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.usuario'),
        ),
        migrations.AddField(
            model_name='unidade_tipopacto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.unidade'),
        ),
        migrations.AddField(
            model_name='tipopacto',
            name='unidades',
            field=models.ManyToManyField(through='configurations.Unidade_TipoPacto', to='configurations.Unidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidades',
            field=models.ManyToManyField(through='configurations.UsuarioGrupolUnidade', to='configurations.Unidade'),
        ),
    ]
