# Generated by Django 3.1.1 on 2021-01-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20210121_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('texto_explicativo', models.TextField(max_length=1000)),
                ('inativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
                ('avaliacao_simplificada', models.BooleanField()),
                ('avaliacao_detalhada', models.BooleanField()),
                ('limite_superior', models.FloatField()),
                ('limite_inferior', models.FloatField()),
                ('conceito', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='grupoatividade',
            name='tipo_pactos',
            field=models.ManyToManyField(to='configurations.TipoPacto'),
        ),
        migrations.CreateModel(
            name='ItemAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('impacto_nota', models.FloatField()),
                ('inativo', models.BooleanField()),
                ('criterio_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.criterioavaliacao')),
                ('nota_maxima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.notaavaliacao')),
            ],
        ),
    ]
